apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bench-task-with-one-step
spec:
  steps:
    - name: step-1
      image: registry.redhat.io/openshift4/ose-cli:v4.12@sha256:9f0cdc00b1b1a3c17411e50653253b9f6bb5329ea4fb82ad983790a6dbf2d9ad 
      command:
        - /bin/sh
      args:
        - -c 
        - "echo  This is a default Tekton pipeline. Tekton is working." 
    