apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bench-three-tasks-with-ten-steps
spec:
  tasks:
  - name: task-1
    taskRef:
      name: bench-task-with-ten-steps
  - name: task-2
    runAfter: [task-1]
    taskRef:
      name: bench-task-with-ten-steps
  - name: task-3
    runAfter: [task-2]
    taskRef:
      name: bench-task-with-ten-steps
