apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bench-seven-tasks-with-one-step-serial
spec:
  tasks:
  - name: task-1
    taskRef:
      name: bench-task-with-one-step
  - name: task-2
    runAfter: [task-1]
    taskRef:
      name: bench-task-with-one-step
  - name: task-3
    runAfter: [task-2]
    taskRef:
      name: bench-task-with-one-step
  - name: task-4
    runAfter: [task-3]
    taskRef:
      name: bench-task-with-one-step
  - name: task-5
    runAfter: [task-4]
    taskRef:
      name: bench-task-with-one-step
  - name: task-6
    runAfter: [task-5]
    taskRef:
      name: bench-task-with-one-step
  - name: task-7
    runAfter: [task-6]
    taskRef:
      name: bench-task-with-one-step
